import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import Header from "@/components/layout/Header";
>>>>>>> ea57380427bbcf2ccf4cf73ba0c50c964b870ccf

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {children}
=======
        <Header />
        <main className="pt-16 h-screen overflow-hidden">
          {children}
        </main>
>>>>>>> ea57380427bbcf2ccf4cf73ba0c50c964b870ccf
      </body>
    </html>
  );
}
